# Generated by Django 4.2.7 on 2026-01-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_slug_alter_product_slug_store_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', models.JSONField(default=dict, help_text='Page sections configuration')),
                ('primary_color', models.CharField(default='#007bff', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#212529', max_length=7)),
                ('font_family', models.CharField(default='Arial, sans-serif', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('layout_width', models.CharField(choices=[('container', 'Boxed'), ('fluid', 'Full Width')], default='container', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='shop.store')),
            ],
            options={
                'verbose_name': 'Store Theme',
                'verbose_name_plural': 'Store Themes',
            },
        ),
    ]
